[build-system]
requires = [ "setuptools >= 77" ]
build-backend = "setuptools.build_meta"

[project]
name = "caife"
description = "Composable and Auto-differentiable Inversion of Fredholm Equations"
dependencies = [
    "jax >= 0.4.25", # the jax.tree API
    "numpy",
    "scipy",
]
requires-python = ">= 3.9"
keywords = [
    "machine learning",
    "supervised learning",
    "quantification",
    "class prevalence estimation",
    "unfolding",
    "astroparticle physics",
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
readme = "README.md"
authors = [
    { name = "Mirko Bunse", email = "mirko.bunse@cs.tu-dortmund.de" },
]
dynamic = [ "version" ]

[project.optional-dependencies]
docs = [ "myst-parser", "scikit-learn", "sphinx-rtd-theme" ]
tests = [ "scikit-learn" ]
notebooks = [ "jupyter", "mpl_interactions[jupyter]", "pandas", "scikit-learn", "tqdm" ]

[tool.setuptools]
include-package-data = false # the package has no data files; otherwise, the excluded tests return as data

[tool.setuptools.packages.find]
include = [ "caife*" ]
exclude = [ "caife.tests*" ]

[tool.setuptools.dynamic]
version = { attr = "caife.__version__" }

[project.urls]
Documentation = "https://mirkobunse.github.io/caife"
Repository = "https://github.com/mirkobunse/caife"
Issues = "https://github.com/mirkobunse/caife/issues"
Changelog = "https://github.com/mirkobunse/caife/releases"
